services:
    py_webapp:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "9084:9083"
        command: "--port 9083"
        cpus: 0.2
        mem_limit: 1024m